### PR TITLE
Show also orphaned processes

### PR DESCRIPTION
**Pull request by climblinne**
Display now also orphaned process and group them together.

### CODE REVIEW

**Comment by randomascii** [comment]
By "orphans" I assume you mean processes whose parents have died, correct? What about processes that are both zombies and orphans? How are they reported.

I tested this on my work machine and it said:
    -30 orphans
        1 orphan of svchost.exe
        -35 orphans of WmiPrvSE.exe
        -1 orphans of LogonUI.exe
        -1 orphans of remoting_desktop.exe
        1 orphan of chrome.exe
        1 orphan of taskhostw.exe
        1 orphan of MicrosoftEdge.exe
        1 orphan of gMenu.exe
        1 orphan of cygwin-console-helper.exe
        1 orphan of ssh-agent.exe

I don't understand the negative numbers. It happens when "orphaned[name.Key] - name.Count();" runs and orphaned[name.Key] is 35 and name.Count() is 70. Any thoughts? If I run as non-admin then I don't get any negatives. Earlier in the output:

    70 zombies held by svchost.exe(1480)
        70 zombies of WmiPrvSE.exe

Any thoughts?

**Comment by randomascii** [comment]
To be clear, there should be a comment (in the change description and in the code) explaining what is meant by orphans.

**Comment by climblinne** [comment]
Hi, I don't really know, why the numbers are getting negative. But I thought for the first implementation it is better to output these as negative numbers, than to cut them at Zero. May be there are orphaned process, that are also parents for other processes?

**Comment by randomascii** [comment]
I could try to analyze whether the negative numbers make sense but for that I would need to understand what the definition of an orphaned process is. If an orphaned process is simply a process with no living parent then should be trivially a non-negative number.

Maybe if you add a comment explaining why you are subtracting name.Count() then that would make it clearer. Right now it feels like a logic bug, but I can't really assess.

**Pull request closed without merging**
